error.data <- list()
error.data["H1168R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1168R.txt",header=T)
error.data["H1260R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1260R.txt",header=T)
error.data["H1266L"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1266L.txt",header=T)
error.data["H1267R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1267R.txt",header=T)
error.data["H1365R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1365R.txt",header=T)
error.data["H1366R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1366R.txt",header=T)
error.data["H1367R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1367R.txt",header=T)
error.data["H1368R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1368R.txt",header=T)
error.data["H1369L"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1369L.txt",header=T)
error.data["H1370R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1370R.txt",header=T)
error.data["H1372R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1372R.txt",header=T)
error.data["H1373R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1373R.txt",header=T)
error.data["H1374R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1374R.txt",header=T)
error.data["H1375L"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1375L.txt",header=T)
error.data["H1376L"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1376L.txt",header=T)
error.data["H1377R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1377R.txt",header=T)
error.data["H1380R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1380R.txt",header=T)
error.data["H1381R"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1381R.txt",header=T)
error.data["H1382L"] <- read.table("/home/seth/Documents/Research/Projects/Open Projects/12-036 Strain Analysis/H1382L.txt",header=T)

boxplot(error.data)
abline(h=0)
mtext(text="Error (%)",side=2,cex=1.5,line=2)

t.results <- lapply(error.data,t.test)
t.stdev <- lapply(error.data,sd)